#ifndef A2SIMPLENAVIGATOR_V1_0_1_GRAPH_ALGORITHMS_ANT_CC
#define A2SIMPLENAVIGATOR_V1_0_1_GRAPH_ALGORITHMS_ANT_CC

namespace s21
{



} // namespace s21


#endif // A2SIMPLENAVIGATOR_V1_0_1_GRAPH_ALGORITHMS_ANT_CC
